# -*- coding: utf-8 -*-
"""data_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmAR0w56md-g3bbpctsE2-eOE43-SiBI
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""#  ANALYSIS QUESTIONS
# 1) what is the relationship of Lethal concentrations to other properties in the dataset?
# 2) Which parameters will cause the water to be more toxic?
# 3) Which of the parameters contributes more to the toxidity of the water?
"""

data=pd.read_csv('toxidity.csv')

data.head()

"""# DATA EXPLORATION"""

data.info()

data.corr()

data.describe()

fig,ax=plt.subplots(figsize=(10,5))
sns.heatmap(data.corr(),annot=True,cmap='viridis')

sns.relplot(data=data,x='MLOGP',y='LC50')

sns.relplot(data=data,x='TPSA',y='LC50')

sns.relplot(data=data,x='Saacc',y='LC50')

sns.pairplot(data)

sns.pairplot(data,kind='kde')

